version: '2'
services:
    server-pool:
        build:
            context: "."
            dockerfile: "Dockerfile.server"
        ports:
            - "8080:8080"
    client-pool:
        build:
            context: "."
            dockerfile: "Dockerfile.client"
        depends_on:
            - "server-pool"
