version: '2.2'
services:
    server-pool:
        build:
            context: "."
            dockerfile: "Dockerfile.server"
        ports:
            - "8080:8080"
        cpu_count: 3
        mem_limit: 4000m
    client-pool:
        build:
            context: "."
            dockerfile: "Dockerfile.client"
        depends_on:
            - "server-pool"
        cpu_count: 2
